export default {
    'moz.pa': 'Moz Page Authority',
    'moz.da': 'Moz Domain Authority',
    'moz.rank': 'Moz Rank',
    'moz.links_in': 'Moz Links In',
    'moz.equity': 'Moz Equity',
    'alexa.rank': 'Alexa Rank',
    'alexa.country_rank': 'Alexa Country Rank',
    'semRush.rank': 'SemRush Rank',
    'semRush.keyword_num': 'SemRush Keywords Number',
    'semRush.traffic_costs': 'SemRush Traffic Costs',
    'majestic.external_backlinks': 'Majestic External Backlinks',
    'majestic.external_gov': 'Majestic External Backlinks GOV',
    'majestic.external_edu': 'Majestic External Backlinks EDU',
    'majestic.cf': 'Majestic Citation Flow',
    'majestic.refd': 'Majestic Referring Domains',
    'majestic.refd_edu': 'Majestic Referring Domains EDU',
    'majestic.refd_gov': 'Majestic Referring Domains GOV',
    'facebook.comments': 'Facebook Comments',
    'facebook.shares': 'Facebook Shares',
    'facebook.reactions': 'Facebook Reactions',
    'ahrefs.rank': 'Ahrefs Rank',
    'ahrefs.dr': 'Ahrefs Domain Rating',
    'ahrefs.ext_backlinks': 'Ahrefs External Backlinks',
    'ahrefs.refd': 'Ahrefs Referring Domains',
    'ahrefs.dofollow': 'Ahrefs Dofollow',
};